name: Dependencies
on:
  workflow_dispatch:
    inputs:
      codesign:
        description: 'Code signing'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - none

jobs:
  package:
    runs-on: windows-2022
    
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Import code signing certificate
        if:  ${{ inputs.codesign == 'test' }} 
        shell: pwsh
        run: |
          $AuthenticodePath = "~\Documents\Authenticode"
          New-Item -ItemType Directory -Path $AuthenticodePath -ErrorAction SilentlyContinue | Out-Null
          $TestCertsUrl = "https://raw.githubusercontent.com/Devolutions/devolutions-authenticode/master/data/certs"
          @('authenticode-test-ca.crt','authenticode-test-cert.pfx') | ForEach-Object {
              Invoke-WebRequest -Uri "$TestCertsUrl/$_" -OutFile $AuthenticodePath\$_
          }
          Import-Certificate -FilePath "$AuthenticodePath\authenticode-test-ca.crt" -CertStoreLocation "cert:\LocalMachine\Root"
          $CodeSignPassword = ConvertTo-SecureString "CodeSign123!" -AsPlainText -Force
          Import-PfxCertificate -FilePath "$AuthenticodePath\authenticode-test-cert.pfx" -CertStoreLocation 'cert:\CurrentUser\My' -Password $CodeSignPassword

          $CodesignThumbprint = Get-ChildItem cert:\CurrentUser\My -CodeSigning | Select-Object -First 1 -ExpandProperty Thumbprint
          echo "CODESIGN_THUMBPRINT=$CodesignThumbprint" >> $Env:GITHUB_ENV
          echo "TIMESTAMP_SERVER=http://timestamp.digicert.com" >> $Env:GITHUB_ENV

      - name: VCRT Forwarders
        shell: pwsh
        run: |
          choco install reshack -y --no-progress
          Install-Module -Name VsDevShell -Force
          Enter-VsDevShell x64
          New-Item -Path .\package -ItemType Directory -Force | Out-Null
          Set-Location .\package
          ..\scripts\FixVCRTForwarders.ps1

      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: wt-dependencies
          path: package/*.nupkg
